apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab-o3s
  creationTimestamp: '2025-06-14T06:51:36Z'
  generation: 1
  labels:
    app: minio
    app.kubernetes.io/managed-by: Helm
    chart: minio-0.4.3
    heritage: Helm
    release: gitlab
  managedFields:
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
        f:spec:
          f:activeDeadlineSeconds: {}
          f:backoffLimit: {}
          f:completionMode: {}
          f:completions: {}
          f:manualSelector: {}
          f:parallelism: {}
          f:podReplacementPolicy: {}
          f:suspend: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
                f:chart: {}
                f:component: {}
                f:heritage: {}
                f:release: {}
            f:spec:
              f:automountServiceAccountToken: {}
              f:containers:
                k:{"name":"minio-mc"}:
                  .: {}
                  f:command: {}
                  f:env:
                    .: {}
                    k:{"name":"HOME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MINIO_ENDPOINT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"MINIO_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources:
                    .: {}
                    f:requests:
                      .: {}
                      f:cpu: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:runAsNonRoot: {}
                    f:runAsUser: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext:
                .: {}
                f:fsGroup: {}
                f:runAsUser: {}
                f:seccompProfile:
                  .: {}
                  f:type: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"minio-configuration"}:
                  .: {}
                  f:name: {}
                  f:projected:
                    .: {}
                    f:defaultMode: {}
                    f:sources: {}
      manager: helm
      operation: Update
      time: '2025-06-14T06:51:36Z'
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:completionTime: {}
          f:conditions: {}
          f:ready: {}
          f:startTime: {}
          f:succeeded: {}
          f:terminating: {}
          f:uncountedTerminatedPods: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-06-14T06:51:40Z'
  name: gitlab-minio-create-buckets-f56d2b3
  namespace: gitlab-o3s
  resourceVersion: '2145327'
  uid: 3859757f-7fc5-483f-ad9e-7565481d217d
spec:
  activeDeadlineSeconds: 600
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: 3859757f-7fc5-483f-ad9e-7565481d217d
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: minio
        batch.kubernetes.io/controller-uid: 3859757f-7fc5-483f-ad9e-7565481d217d
        batch.kubernetes.io/job-name: gitlab-minio-create-buckets-f56d2b3
        chart: minio-0.4.3
        component: create-buckets
        controller-uid: 3859757f-7fc5-483f-ad9e-7565481d217d
        heritage: Helm
        job-name: gitlab-minio-create-buckets-f56d2b3
        release: gitlab
    spec:
      automountServiceAccountToken: false
      containers:
        - command:
            - /bin/sh
            - /config/initialize
          env:
            - name: HOME
              value: /tmp
            - name: MINIO_ENDPOINT
              value: gitlab-minio-svc.gitlab-o3s.svc
            - name: MINIO_PORT
              value: '9000'
          image: minio/mc:RELEASE.2018-07-13T00-53-22Z
          imagePullPolicy: IfNotPresent
          name: minio-mc
          resources:
            requests:
              cpu: 50m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config
              name: minio-configuration
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      volumes:
        - name: minio-configuration
          projected:
            defaultMode: 420
            sources:
              - configMap:
                  name: gitlab-minio-config-cm
              - secret:
                  name: gitlab-minio-secret
status:
  completionTime: '2025-06-14T06:51:40Z'
  conditions:
    - lastProbeTime: '2025-06-14T06:51:40Z'
      lastTransitionTime: '2025-06-14T06:51:40Z'
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: 'True'
      type: SuccessCriteriaMet
    - lastProbeTime: '2025-06-14T06:51:40Z'
      lastTransitionTime: '2025-06-14T06:51:40Z'
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: 'True'
      type: Complete
  ready: 0
  startTime: '2025-06-14T06:51:36Z'
  succeeded: 1
  terminating: 0
  uncountedTerminatedPods: {}
