apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    objectset.rio.cattle.io/applied: >-
      H4sIAAAAAAAA/7RXXZOiPBb+K1u5BgSxdbSqL2jFbXdstcCZ2q2pLiuEo2YNCZsEZ9wu//tbAbobP/rr4r2TkOfhfD7n+IRwTn+CVFRwNEAJ1mTb2nvIQjvKUzRA/xIJslAGGqdYYzR4QphzobGmgivzKJL/AtEKtCOpcAjWmoFDRYsa9BZYZhPBtRSMgbTJFkttS9hQpWXJgaw3GcRvDtLe7Hc1UePV3rP+8Z3y9PYeWDY0pB/ycJwBGiC5g7ZNMKNE2ESmn4KpHBOD3RUJ2OqgNGToaCEioXRhSTNQGmc5GvCCMQsxnAArg2PMLn1WzpkH5emX7NlitTUpard9nKyTNAHs9W66nt/pEB/7a+jBN9IF7Pp+4qepsbD2ucwC5UpjxuzLD77looXKEESwBgmcgEKDX2f1cpEWZKGECbKbG+QIGJQ5HqwxU2Ch10p4OarLrJnHNzNVlDXl9ZL+uu+5Nk59Ynf638DGSRfstO0lOPX73S7poePj0UIqB2KykGCyE+v1lGZUo4Hnuq6FNGQ5wxrM+3eq+50ECr6mm/sqKfF90L7p3na+Be273vimHfjfOq5/F9zdDb3+sB/2wm7vLhz5wfhm7I28Xj/odDr97nA8bPfHvbH7t5XTsREGE31MOcg6kXJjfqC6MJCFbFuBtpWWlG+QhTZMJJg9f6QqihGsccF0VHXw4bZu5YMjMSdbkA4R2dtMrFAa5HAyim491+m0HddxW173M4B950uQ0Swu7/uO63juh7dFhim/rZ8cJgh+Ox4mxCOs8YjK29YeyxajSat2v2VevolUIPeUwIv//kfOnMR8wjcSlBoyrNQtrR5svqH8z+fw7+fs0ULA92Vh1P03Cx5CZKE9ZsW1djxaLzd/hlE8mc+aR1G4mDef78Ppw2oUTX6GUYNTAZGgm/eG90G0XJlPx4tg2Pz+qfieAi6+dMWiZRD9M/wSdfBjeb9aBHG8GkbhKJwtJ8E0bsBKBWsCJrM4HP6IwlX8fbJYLaexsWMy/s97mMU0mMxW98vl4r1b33/chdEsXIbxKg6jn5NhuLqfx8sGxGv3TDU53gewxTxqwrqdjt9E3M3ny3gZBU1rtCxOjJnNV4to/u+mW47aE8s56R+r2a7WSbk3uMbBZGoitphPJ8Mmo4RnXTo+WohmeFOdXpbuS+/tGM1zkLaRxsHedfrOjZ0UlKVtt33j+q7ps5JoUTC2EIySg0naeib0QoIC3hg+hgNZSIIShSxH35NRUiCFpPowFFzDH13OC8bE74Wke8pgA6EimOHTmYdznFBGNS1ZUCpFbmQ3mE6RGVIScDrn7BAJoceUQV2HAxP1o4X2ghUZPIiC60q2M/NzgbUZO62tyODE75ZTW1770XxXxv0jOMFkC5f46vhTBOVcvMJQnV9Q6Cx/vWweLm6cM5Yloq7cO90fzLgzOT0+mgraCqVnoH8LuatiayEuUoiBAdFCmswYGZAcNKhy/VNogBjlhZFXc9WWgoFzeqleaOycYd5oFVM3Gkv9UmRzPsaUFdJE9koRyYIHaia4qYFn6xQQIrJ8IcWasnJN0Ye8lNaCa5pBrerVhK8GS0CIicessfVdLlFaMJDPC86vJwTrNRCzOsxETLaQFswYuQNjtnH7zGMuzP6O00MZ/6+CqwTYBcd7TBlOGHyOhjBRpLkUe5qCPCMtOOVUU8zo/6Hcn3Pjn0kpCv9XlIP8Qskq6qGkmhLMgjQVXJkmPIP/oUqrcwvDP0AKfWrgtdoATc7Nucp31eOPi+0q8+OzYNS5zXJ9GFFZLbkpLTI0QA+QCXlo/D240IivwV6l4Yu4V0H4HPBZHE5lwEK5FOYfE6QG/qLXv56e14vBC6T6+1kBL1rjeHw8GvrKrgecXwBrRblEXtOcsi811kU5O45/BQAA//939ylDaQ8AAA
    objectset.rio.cattle.io/id: helm-controller-chart-registration
    objectset.rio.cattle.io/owner-gvk: helm.cattle.io/v1, Kind=HelmChart
    objectset.rio.cattle.io/owner-name: rke2-calico-crd
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: '2025-06-10T20:16:22Z'
  generation: 1
  labels:
    helmcharts.helm.cattle.io/chart: rke2-calico-crd
    objectset.rio.cattle.io/hash: b223abfbdbea17561344c3a3fe7e8c6ea033b3dd
  managedFields:
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:objectset.rio.cattle.io/applied: {}
            f:objectset.rio.cattle.io/id: {}
            f:objectset.rio.cattle.io/owner-gvk: {}
            f:objectset.rio.cattle.io/owner-name: {}
            f:objectset.rio.cattle.io/owner-namespace: {}
          f:labels:
            .: {}
            f:helmcharts.helm.cattle.io/chart: {}
            f:objectset.rio.cattle.io/hash: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"17b9f910-ad3c-498e-ab6e-d21bad3966c7"}: {}
        f:spec:
          f:backoffLimit: {}
          f:completionMode: {}
          f:completions: {}
          f:manualSelector: {}
          f:parallelism: {}
          f:podReplacementPolicy: {}
          f:suspend: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:helmcharts.helm.cattle.io/configHash: {}
              f:labels:
                .: {}
                f:helmcharts.helm.cattle.io/chart: {}
            f:spec:
              f:containers:
                k:{"name":"helm"}:
                  .: {}
                  f:args: {}
                  f:env:
                    .: {}
                    k:{"name":"AUTH_PASS_CREDENTIALS"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"BOOTSTRAP"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"CHART"}:
                      .: {}
                      f:name: {}
                    k:{"name":"CHART_NAMESPACE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"FAILURE_POLICY"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"HELM_DRIVER"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"HELM_VERSION"}:
                      .: {}
                      f:name: {}
                    k:{"name":"INSECURE_SKIP_TLS_VERIFY"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBERNETES_SERVICE_HOST"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"KUBERNETES_SERVICE_PORT"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"NO_PROXY"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"PLAIN_HTTP"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"REPO"}:
                      .: {}
                      f:name: {}
                    k:{"name":"TARGET_NAMESPACE"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"VERSION"}:
                      .: {}
                      f:name: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:readOnlyRootFilesystem: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/chart"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/home/klipper-helm/.cache"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/home/klipper-helm/.config"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/home/klipper-helm/.helm"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
                    k:{"mountPath":"/tmp"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:hostNetwork: {}
              f:nodeSelector: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext:
                .: {}
                f:runAsNonRoot: {}
                f:seccompProfile:
                  .: {}
                  f:type: {}
              f:serviceAccount: {}
              f:serviceAccountName: {}
              f:terminationGracePeriodSeconds: {}
              f:tolerations: {}
              f:volumes:
                .: {}
                k:{"name":"content"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
                k:{"name":"klipper-cache"}:
                  .: {}
                  f:emptyDir:
                    .: {}
                    f:medium: {}
                  f:name: {}
                k:{"name":"klipper-config"}:
                  .: {}
                  f:emptyDir:
                    .: {}
                    f:medium: {}
                  f:name: {}
                k:{"name":"klipper-helm"}:
                  .: {}
                  f:emptyDir:
                    .: {}
                    f:medium: {}
                  f:name: {}
                k:{"name":"tmp"}:
                  .: {}
                  f:emptyDir:
                    .: {}
                    f:medium: {}
                  f:name: {}
                k:{"name":"values"}:
                  .: {}
                  f:name: {}
                  f:projected:
                    .: {}
                    f:defaultMode: {}
                    f:sources: {}
      manager: helm-controller@gitlab-pointer-pool1-2pdwj-trhvb
      operation: Update
      time: '2025-06-10T20:16:22Z'
    - apiVersion: batch/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:completionTime: {}
          f:conditions: {}
          f:ready: {}
          f:startTime: {}
          f:succeeded: {}
          f:terminating: {}
          f:uncountedTerminatedPods: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-06-10T20:16:37Z'
  name: helm-install-rke2-calico-crd
  namespace: kube-system
  ownerReferences:
    - apiVersion: helm.cattle.io/v1
      blockOwnerDeletion: false
      controller: false
      kind: HelmChart
      name: rke2-calico-crd
      uid: 17b9f910-ad3c-498e-ab6e-d21bad3966c7
  resourceVersion: '853'
  uid: e9f8f6ca-dff6-48a5-ba52-f37b6213d3e8
spec:
  backoffLimit: 1000
  completionMode: NonIndexed
  completions: 1
  manualSelector: false
  parallelism: 1
  podReplacementPolicy: TerminatingOrFailed
  selector:
    matchLabels:
      batch.kubernetes.io/controller-uid: e9f8f6ca-dff6-48a5-ba52-f37b6213d3e8
  suspend: false
  template:
    metadata:
      annotations:
        helmcharts.helm.cattle.io/configHash: >-
          SHA256=48A2B7F52A38403BABBC19C9E7E67BED3AF5F1D179A44496CFC29F7F0ECB1DD9
      creationTimestamp: null
      labels:
        batch.kubernetes.io/controller-uid: e9f8f6ca-dff6-48a5-ba52-f37b6213d3e8
        batch.kubernetes.io/job-name: helm-install-rke2-calico-crd
        controller-uid: e9f8f6ca-dff6-48a5-ba52-f37b6213d3e8
        helmcharts.helm.cattle.io/chart: rke2-calico-crd
        job-name: helm-install-rke2-calico-crd
    spec:
      containers:
        - args:
            - install
            - '--set-string'
            - global.cattle.systemDefaultRegistry=registry.rancher.com
            - '--set-string'
            - global.clusterCIDR=10.42.0.0/16
            - '--set-string'
            - global.clusterCIDRv4=10.42.0.0/16
            - '--set-string'
            - global.clusterDNS=10.43.0.10
            - '--set-string'
            - global.clusterDomain=cluster.local
            - '--set-string'
            - global.rke2DataDir=/var/lib/rancher/rke2
            - '--set-string'
            - global.serviceCIDR=10.43.0.0/16
            - '--set-string'
            - global.systemDefaultIngressClass=ingress-nginx
            - '--set-string'
            - global.systemDefaultRegistry=registry.rancher.com
          env:
            - name: NAME
              value: rke2-calico-crd
            - name: VERSION
            - name: REPO
            - name: HELM_DRIVER
              value: secret
            - name: CHART_NAMESPACE
              value: kube-system
            - name: CHART
            - name: HELM_VERSION
            - name: TARGET_NAMESPACE
              value: kube-system
            - name: AUTH_PASS_CREDENTIALS
              value: 'false'
            - name: INSECURE_SKIP_TLS_VERIFY
              value: 'false'
            - name: PLAIN_HTTP
              value: 'false'
            - name: KUBERNETES_SERVICE_HOST
              value: 127.0.0.1
            - name: KUBERNETES_SERVICE_PORT
              value: '6443'
            - name: BOOTSTRAP
              value: 'true'
            - name: NO_PROXY
              value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
            - name: FAILURE_POLICY
              value: reinstall
          image: registry.rancher.com/rancher/klipper-helm:v0.9.5-build20250306
          imagePullPolicy: IfNotPresent
          name: helm
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /home/klipper-helm/.helm
              name: klipper-helm
            - mountPath: /home/klipper-helm/.cache
              name: klipper-cache
            - mountPath: /home/klipper-helm/.config
              name: klipper-config
            - mountPath: /tmp
              name: tmp
            - mountPath: /config
              name: values
            - mountPath: /chart
              name: content
      dnsPolicy: ClusterFirst
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: 'true'
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: helm-rke2-calico-crd
      serviceAccountName: helm-rke2-calico-crd
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/not-ready
        - effect: NoSchedule
          key: node.kubernetes.io/network-unavailable
        - effect: NoSchedule
          key: node.cloudprovider.kubernetes.io/uninitialized
          operator: Equal
          value: 'true'
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          key: node-role.kubernetes.io/etcd
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
      volumes:
        - emptyDir:
            medium: Memory
          name: klipper-helm
        - emptyDir:
            medium: Memory
          name: klipper-cache
        - emptyDir:
            medium: Memory
          name: klipper-config
        - emptyDir:
            medium: Memory
          name: tmp
        - name: values
          projected:
            defaultMode: 420
            sources:
              - secret:
                  name: chart-values-rke2-calico-crd
        - configMap:
            defaultMode: 420
            name: chart-content-rke2-calico-crd
          name: content
status:
  completionTime: '2025-06-10T20:16:37Z'
  conditions:
    - lastProbeTime: '2025-06-10T20:16:37Z'
      lastTransitionTime: '2025-06-10T20:16:37Z'
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: 'True'
      type: SuccessCriteriaMet
    - lastProbeTime: '2025-06-10T20:16:37Z'
      lastTransitionTime: '2025-06-10T20:16:37Z'
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: 'True'
      type: Complete
  ready: 0
  startTime: '2025-06-10T20:16:22Z'
  succeeded: 1
  terminating: 0
  uncountedTerminatedPods: {}
