apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    meta.helm.sh/release-name: gitlab
    meta.helm.sh/release-namespace: gitlab-o3s
  creationTimestamp: '2025-06-13T15:46:15Z'
  generation: 1
  labels:
    app: sidekiq
    app.kubernetes.io/managed-by: Helm
    chart: sidekiq-9.0.2
    heritage: Helm
    release: gitlab
  managedFields:
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
        f:spec:
          f:maxUnavailable: {}
          f:selector: {}
      manager: helm
      operation: Update
      time: '2025-06-13T15:46:15Z'
    - apiVersion: policy/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"DisruptionAllowed"}:
              .: {}
              f:lastTransitionTime: {}
              f:message: {}
              f:observedGeneration: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:currentHealthy: {}
          f:disruptionsAllowed: {}
          f:expectedPods: {}
          f:observedGeneration: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-06-14T01:38:53Z'
  name: gitlab-sidekiq-all-in-1-v1
  namespace: gitlab-o3s
  resourceVersion: '2024222'
  uid: f2075827-9b4f-4830-b688-b74b1cf653ab
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: sidekiq
      queue-pod-name: all-in-1
      release: gitlab
status:
  conditions:
    - lastTransitionTime: '2025-06-13T15:48:48Z'
      message: ''
      observedGeneration: 1
      reason: SufficientPods
      status: 'True'
      type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
