apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 2540cb8d2d5c293e9a37ec3f7cf2ed1693a3e5891b0d39938344f5f78630353f
    cni.projectcalico.org/podIP: ''
    cni.projectcalico.org/podIPs: ''
  creationTimestamp: '2025-06-14T06:51:36Z'
  generateName: gitlab-minio-create-buckets-f56d2b3-
  labels:
    app: minio
    batch.kubernetes.io/controller-uid: 3859757f-7fc5-483f-ad9e-7565481d217d
    batch.kubernetes.io/job-name: gitlab-minio-create-buckets-f56d2b3
    chart: minio-0.4.3
    component: create-buckets
    controller-uid: 3859757f-7fc5-483f-ad9e-7565481d217d
    heritage: Helm
    job-name: gitlab-minio-create-buckets-f56d2b3
    release: gitlab
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:batch.kubernetes.io/controller-uid: {}
            f:batch.kubernetes.io/job-name: {}
            f:chart: {}
            f:component: {}
            f:controller-uid: {}
            f:heritage: {}
            f:job-name: {}
            f:release: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"3859757f-7fc5-483f-ad9e-7565481d217d"}: {}
        f:spec:
          f:automountServiceAccountToken: {}
          f:containers:
            k:{"name":"minio-mc"}:
              .: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"HOME"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"MINIO_ENDPOINT"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"MINIO_PORT"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:cpu: {}
              f:securityContext:
                .: {}
                f:allowPrivilegeEscalation: {}
                f:capabilities:
                  .: {}
                  f:drop: {}
                f:runAsNonRoot: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/config"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext:
            .: {}
            f:fsGroup: {}
            f:runAsUser: {}
            f:seccompProfile:
              .: {}
              f:type: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"minio-configuration"}:
              .: {}
              f:name: {}
              f:projected:
                .: {}
                f:defaultMode: {}
                f:sources: {}
      manager: kube-controller-manager
      operation: Update
      time: '2025-06-14T06:51:36Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:cni.projectcalico.org/containerID: {}
            f:cni.projectcalico.org/podIP: {}
            f:cni.projectcalico.org/podIPs: {}
      manager: calico
      operation: Update
      subresource: status
      time: '2025-06-14T06:51:39Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodReadyToStartContainers"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:hostIPs: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.42.4.188"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      subresource: status
      time: '2025-06-14T06:51:39Z'
  name: gitlab-minio-create-buckets-f56d2b3-s86cr
  namespace: gitlab-o3s
  ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: gitlab-minio-create-buckets-f56d2b3
      uid: 3859757f-7fc5-483f-ad9e-7565481d217d
  resourceVersion: '2145325'
  uid: 03646410-efe3-48cf-98f8-b7c8baa3c32f
spec:
  automountServiceAccountToken: false
  containers:
    - command:
        - /bin/sh
        - /config/initialize
      env:
        - name: HOME
          value: /tmp
        - name: MINIO_ENDPOINT
          value: gitlab-minio-svc.gitlab-o3s.svc
        - name: MINIO_PORT
          value: '9000'
      image: minio/mc:RELEASE.2018-07-13T00-53-22Z
      imagePullPolicy: IfNotPresent
      name: minio-mc
      resources:
        requests:
          cpu: 50m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /config
          name: minio-configuration
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gitlab-pointer-pool1-cczkf-vbgtv
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: minio-configuration
      projected:
        defaultMode: 420
        sources:
          - configMap:
              name: gitlab-minio-config-cm
          - secret:
              name: gitlab-minio-secret
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:39Z'
      status: 'False'
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:36Z'
      reason: PodCompleted
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:36Z'
      reason: PodCompleted
      status: 'False'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:36Z'
      reason: PodCompleted
      status: 'False'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:36Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        containerd://f064e1c8e6419a678cc38e50f9167b2fe42ec36150bf6842194eebe8c38c1595
      image: docker.io/minio/mc:RELEASE.2018-07-13T00-53-22Z
      imageID: >-
        docker.io/minio/mc@sha256:88890e23ba30a056293bf4e83563d18ac51b4102e784c939db541bcca53c05ac
      lastState: {}
      name: minio-mc
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: >-
            containerd://f064e1c8e6419a678cc38e50f9167b2fe42ec36150bf6842194eebe8c38c1595
          exitCode: 0
          finishedAt: '2025-06-14T06:51:37Z'
          reason: Completed
          startedAt: '2025-06-14T06:51:37Z'
      volumeMounts:
        - mountPath: /config
          name: minio-configuration
  hostIP: 172.31.36.39
  hostIPs:
    - ip: 172.31.36.39
  phase: Succeeded
  podIP: 10.42.4.188
  podIPs:
    - ip: 10.42.4.188
  qosClass: Burstable
  startTime: '2025-06-14T06:51:36Z'
