apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 0115cdcad5246cfe9cc5d6f1fd4d57d823084aa3f775046d5657963c2064fd38
    cni.projectcalico.org/podIP: ''
    cni.projectcalico.org/podIPs: ''
  creationTimestamp: '2025-06-14T06:51:36Z'
  generateName: gitlab-migrations-bef0650-
  labels:
    app: migrations
    batch.kubernetes.io/controller-uid: a986cefc-56af-41eb-bf00-33cfa8bdfb00
    batch.kubernetes.io/job-name: gitlab-migrations-bef0650
    chart: migrations-9.0.2
    controller-uid: a986cefc-56af-41eb-bf00-33cfa8bdfb00
    heritage: Helm
    job-name: gitlab-migrations-bef0650
    release: gitlab
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:generateName: {}
          f:labels:
            .: {}
            f:app: {}
            f:batch.kubernetes.io/controller-uid: {}
            f:batch.kubernetes.io/job-name: {}
            f:chart: {}
            f:controller-uid: {}
            f:heritage: {}
            f:job-name: {}
            f:release: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"a986cefc-56af-41eb-bf00-33cfa8bdfb00"}: {}
        f:spec:
          f:automountServiceAccountToken: {}
          f:containers:
            k:{"name":"migrations"}:
              .: {}
              f:args: {}
              f:env:
                .: {}
                k:{"name":"BYPASS_SCHEMA_VERSION"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"CONFIG_DIRECTORY"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"CONFIG_TEMPLATE_DIRECTORY"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"ENABLE_BOOTSNAP"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"TZ"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
              f:securityContext:
                .: {}
                f:allowPrivilegeEscalation: {}
                f:capabilities:
                  .: {}
                  f:drop: {}
                f:runAsNonRoot: {}
                f:runAsUser: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/etc/gitlab"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/etc/pki/ca-trust/extracted/pem"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/etc/ssl/certs/"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/srv/gitlab/config/gitlab_shared_runners_registration_token"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:subPath: {}
                k:{"mountPath":"/srv/gitlab/config/initial_root_password"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:subPath: {}
                k:{"mountPath":"/srv/gitlab/config/secrets.yml"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:subPath: {}
                k:{"mountPath":"/var/opt/gitlab/templates"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:initContainers:
            .: {}
            k:{"name":"certificates"}:
              .: {}
              f:env:
                .: {}
                k:{"name":"TZ"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:cpu: {}
              f:securityContext:
                .: {}
                f:allowPrivilegeEscalation: {}
                f:capabilities:
                  .: {}
                  f:drop: {}
                f:runAsNonRoot: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/etc/pki/ca-trust/extracted/pem"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                k:{"mountPath":"/etc/ssl/certs"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
            k:{"name":"configure"}:
              .: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"TZ"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:name: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:cpu: {}
              f:securityContext:
                .: {}
                f:allowPrivilegeEscalation: {}
                f:capabilities:
                  .: {}
                  f:drop: {}
                f:runAsNonRoot: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/config"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/init-config"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/init-secrets"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext:
            .: {}
            f:fsGroup: {}
            f:runAsUser: {}
            f:seccompProfile:
              .: {}
              f:type: {}
          f:terminationGracePeriodSeconds: {}
          f:volumes:
            .: {}
            k:{"name":"etc-pki-ca-trust-extracted-pem"}:
              .: {}
              f:emptyDir:
                .: {}
                f:medium: {}
              f:name: {}
            k:{"name":"etc-ssl-certs"}:
              .: {}
              f:emptyDir:
                .: {}
                f:medium: {}
              f:name: {}
            k:{"name":"init-migrations-secrets"}:
              .: {}
              f:name: {}
              f:projected:
                .: {}
                f:defaultMode: {}
                f:sources: {}
            k:{"name":"migrations-config"}:
              .: {}
              f:configMap:
                .: {}
                f:defaultMode: {}
                f:name: {}
              f:name: {}
            k:{"name":"migrations-secrets"}:
              .: {}
              f:emptyDir:
                .: {}
                f:medium: {}
              f:name: {}
      manager: kube-controller-manager
      operation: Update
      time: '2025-06-14T06:51:36Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:cni.projectcalico.org/containerID: {}
            f:cni.projectcalico.org/podIP: {}
            f:cni.projectcalico.org/podIPs: {}
      manager: calico
      operation: Update
      subresource: status
      time: '2025-06-14T06:52:29Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodReadyToStartContainers"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:hostIPs: {}
          f:initContainerStatuses: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"10.42.152.150"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      subresource: status
      time: '2025-06-14T06:52:29Z'
  name: gitlab-migrations-bef0650-95xt6
  namespace: gitlab-o3s
  ownerReferences:
    - apiVersion: batch/v1
      blockOwnerDeletion: true
      controller: true
      kind: Job
      name: gitlab-migrations-bef0650
      uid: a986cefc-56af-41eb-bf00-33cfa8bdfb00
  resourceVersion: '2145772'
  uid: 37405677-8ab3-4692-a673-ac69c139c600
spec:
  automountServiceAccountToken: false
  containers:
    - args:
        - /bin/bash
        - '-c'
        - |
          set -e;
          /scripts/wait-for-deps;
          /scripts/db-migrate;
                              
      env:
        - name: CONFIG_TEMPLATE_DIRECTORY
          value: /var/opt/gitlab/templates
        - name: CONFIG_DIRECTORY
          value: /srv/gitlab/config
        - name: BYPASS_SCHEMA_VERSION
          value: 'true'
        - name: ENABLE_BOOTSNAP
          value: '1'
        - name: TZ
          value: America/Sao_Paulo
      image: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v18.0.2
      imagePullPolicy: IfNotPresent
      name: migrations
      resources:
        requests:
          cpu: 250m
          memory: 200Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
        runAsUser: 1000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/opt/gitlab/templates
          name: migrations-config
        - mountPath: /etc/gitlab
          name: migrations-secrets
          readOnly: true
        - mountPath: /srv/gitlab/config/secrets.yml
          name: migrations-secrets
          subPath: rails-secrets/secrets.yml
        - mountPath: /srv/gitlab/config/initial_root_password
          name: migrations-secrets
          subPath: migrations/initial_root_password
        - mountPath: /srv/gitlab/config/gitlab_shared_runners_registration_token
          name: migrations-secrets
          subPath: migrations/gitlab_shared_runners_registration_token
        - mountPath: /etc/ssl/certs/
          name: etc-ssl-certs
          readOnly: true
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: etc-pki-ca-trust-extracted-pem
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
    - env:
        - name: TZ
          value: America/Sao_Paulo
      image: registry.gitlab.com/gitlab-org/build/cng/certificates:v18.0.2
      imagePullPolicy: IfNotPresent
      name: certificates
      resources:
        requests:
          cpu: 50m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /etc/ssl/certs
          name: etc-ssl-certs
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: etc-pki-ca-trust-extracted-pem
    - command:
        - sh
        - /config/configure
      env:
        - name: TZ
          value: America/Sao_Paulo
      image: registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v18.0.2
      imagePullPolicy: IfNotPresent
      name: configure
      resources:
        requests:
          cpu: 50m
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        runAsNonRoot: true
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /config
          name: migrations-config
          readOnly: true
        - mountPath: /init-config
          name: init-migrations-secrets
          readOnly: true
        - mountPath: /init-secrets
          name: migrations-secrets
  nodeName: gitlab-pointer-pool1-cczkf-rc752
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: OnFailure
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - configMap:
        defaultMode: 420
        name: gitlab-migrations
      name: migrations-config
    - name: init-migrations-secrets
      projected:
        defaultMode: 256
        sources:
          - secret:
              items:
                - key: secrets.yml
                  path: rails-secrets/secrets.yml
              name: gitlab-rails-secret
          - secret:
              items:
                - key: token
                  path: gitaly/gitaly_token
              name: gitlab-gitaly-secret
          - secret:
              items:
                - key: postgresql-postgres-password
                  path: postgres/psql-password-ci
              name: gitlab-postgresql-password
          - secret:
              items:
                - key: postgresql-postgres-password
                  path: postgres/psql-password-main
              name: gitlab-postgresql-password
          - secret:
              items:
                - key: password
                  path: migrations/initial_root_password
              name: gitlab-gitlab-initial-root-password
          - secret:
              items:
                - key: runner-registration-token
                  path: migrations/gitlab_shared_runners_registration_token
              name: gitlab-gitlab-runner-secret
              optional: true
    - emptyDir:
        medium: Memory
      name: migrations-secrets
    - emptyDir:
        medium: Memory
      name: etc-ssl-certs
    - emptyDir:
        medium: Memory
      name: etc-pki-ca-trust-extracted-pem
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:52:29Z'
      status: 'False'
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:39Z'
      reason: PodCompleted
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:52:28Z'
      reason: PodCompleted
      status: 'False'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:52:28Z'
      reason: PodCompleted
      status: 'False'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2025-06-14T06:51:36Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        containerd://b93c8d88e2d5aec477e477ff8eeca38c8beebec9d2838b5dd423a1803b83f9cd
      image: registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee:v18.0.2
      imageID: >-
        registry.gitlab.com/gitlab-org/build/cng/gitlab-toolbox-ee@sha256:66e483dd2251e004921a1953f8c4c9f5437d97cdd598c5e5b56aecb4b10d3c29
      lastState: {}
      name: migrations
      ready: false
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: >-
            containerd://b93c8d88e2d5aec477e477ff8eeca38c8beebec9d2838b5dd423a1803b83f9cd
          exitCode: 0
          finishedAt: '2025-06-14T06:52:27Z'
          reason: Completed
          startedAt: '2025-06-14T06:51:39Z'
      volumeMounts:
        - mountPath: /var/opt/gitlab/templates
          name: migrations-config
        - mountPath: /etc/gitlab
          name: migrations-secrets
          readOnly: true
          recursiveReadOnly: Disabled
        - mountPath: /srv/gitlab/config/secrets.yml
          name: migrations-secrets
        - mountPath: /srv/gitlab/config/initial_root_password
          name: migrations-secrets
        - mountPath: /srv/gitlab/config/gitlab_shared_runners_registration_token
          name: migrations-secrets
        - mountPath: /etc/ssl/certs/
          name: etc-ssl-certs
          readOnly: true
          recursiveReadOnly: Disabled
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: etc-pki-ca-trust-extracted-pem
          readOnly: true
          recursiveReadOnly: Disabled
  hostIP: 172.31.36.13
  hostIPs:
    - ip: 172.31.36.13
  initContainerStatuses:
    - containerID: >-
        containerd://88037c62c8524a550ee5550f380c6a78a9e3f1f07e607b38e8fadbf1439b8566
      image: registry.gitlab.com/gitlab-org/build/cng/certificates:v18.0.2
      imageID: >-
        registry.gitlab.com/gitlab-org/build/cng/certificates@sha256:34ad8bab50a96e4a73167ebf57a343947e9ff3219dfd4361baa6f202bac13dcb
      lastState: {}
      name: certificates
      ready: true
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: >-
            containerd://88037c62c8524a550ee5550f380c6a78a9e3f1f07e607b38e8fadbf1439b8566
          exitCode: 0
          finishedAt: '2025-06-14T06:51:38Z'
          reason: Completed
          startedAt: '2025-06-14T06:51:37Z'
      volumeMounts:
        - mountPath: /etc/ssl/certs
          name: etc-ssl-certs
        - mountPath: /etc/pki/ca-trust/extracted/pem
          name: etc-pki-ca-trust-extracted-pem
    - containerID: >-
        containerd://bf50a033535bb251ed40d0be8289c139f7bda4f1824d57749fb9f32b4310e951
      image: registry.gitlab.com/gitlab-org/build/cng/gitlab-base:v18.0.2
      imageID: >-
        registry.gitlab.com/gitlab-org/build/cng/gitlab-base@sha256:a309b4b65fe9c6882589c60fd8a5d6680e96f741592d61d340fd1b51a0701388
      lastState: {}
      name: configure
      ready: true
      restartCount: 0
      started: false
      state:
        terminated:
          containerID: >-
            containerd://bf50a033535bb251ed40d0be8289c139f7bda4f1824d57749fb9f32b4310e951
          exitCode: 0
          finishedAt: '2025-06-14T06:51:38Z'
          reason: Completed
          startedAt: '2025-06-14T06:51:38Z'
      volumeMounts:
        - mountPath: /config
          name: migrations-config
          readOnly: true
          recursiveReadOnly: Disabled
        - mountPath: /init-config
          name: init-migrations-secrets
          readOnly: true
          recursiveReadOnly: Disabled
        - mountPath: /init-secrets
          name: migrations-secrets
  phase: Succeeded
  podIP: 10.42.152.150
  podIPs:
    - ip: 10.42.152.150
  qosClass: Burstable
  startTime: '2025-06-14T06:51:36Z'
