apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: f6825eac042aa1ccdd1d9863cc09512e
    kubernetes.io/config.mirror: f6825eac042aa1ccdd1d9863cc09512e
    kubernetes.io/config.seen: '2025-06-12T07:31:07.272605914Z'
    kubernetes.io/config.source: file
  creationTimestamp: '2025-06-12T07:31:59Z'
  labels:
    component: kube-scheduler
    tier: control-plane
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubernetes.io/config.hash: {}
            f:kubernetes.io/config.mirror: {}
            f:kubernetes.io/config.seen: {}
            f:kubernetes.io/config.source: {}
          f:labels:
            .: {}
            f:component: {}
            f:tier: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"db6214ad-a078-4bc4-adf6-48ab1c429981"}: {}
        f:spec:
          f:containers:
            k:{"name":"kube-scheduler"}:
              .: {}
              f:args: {}
              f:command: {}
              f:env:
                .: {}
                k:{"name":"FILE_HASH"}:
                  .: {}
                  f:name: {}
                  f:value: {}
                k:{"name":"NO_PROXY"}:
                  .: {}
                  f:name: {}
                  f:value: {}
              f:image: {}
              f:imagePullPolicy: {}
              f:livenessProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:host: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:initialDelaySeconds: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:name: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
              f:securityContext:
                .: {}
                f:privileged: {}
              f:startupProbe:
                .: {}
                f:failureThreshold: {}
                f:httpGet:
                  .: {}
                  f:host: {}
                  f:path: {}
                  f:port: {}
                  f:scheme: {}
                f:initialDelaySeconds: {}
                f:periodSeconds: {}
                f:successThreshold: {}
                f:timeoutSeconds: {}
              f:terminationMessagePath: {}
              f:terminationMessagePolicy: {}
              f:volumeMounts:
                .: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/db/etcd/name"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/tls/client-scheduler.crt"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/tls/client-scheduler.key"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/tls/kube-scheduler"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
                k:{"mountPath":"/var/lib/rancher/rke2/server/tls/server-ca.crt"}:
                  .: {}
                  f:mountPath: {}
                  f:name: {}
                  f:readOnly: {}
          f:dnsPolicy: {}
          f:enableServiceLinks: {}
          f:hostNetwork: {}
          f:nodeName: {}
          f:priorityClassName: {}
          f:restartPolicy: {}
          f:schedulerName: {}
          f:securityContext: {}
          f:terminationGracePeriodSeconds: {}
          f:tolerations: {}
          f:volumes:
            .: {}
            k:{"name":"extra-mount-0"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file0"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file1"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file2"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file3"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file4"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file5"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
            k:{"name":"file6"}:
              .: {}
              f:hostPath:
                .: {}
                f:path: {}
                f:type: {}
              f:name: {}
      manager: kubelet
      operation: Update
      time: '2025-06-12T07:31:59Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:conditions:
            .: {}
            k:{"type":"ContainersReady"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Initialized"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodReadyToStartContainers"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"PodScheduled"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
            k:{"type":"Ready"}:
              .: {}
              f:lastProbeTime: {}
              f:lastTransitionTime: {}
              f:status: {}
              f:type: {}
          f:containerStatuses: {}
          f:hostIP: {}
          f:hostIPs: {}
          f:phase: {}
          f:podIP: {}
          f:podIPs:
            .: {}
            k:{"ip":"172.31.36.13"}:
              .: {}
              f:ip: {}
          f:startTime: {}
      manager: kubelet
      operation: Update
      subresource: status
      time: '2025-06-12T15:36:20Z'
  name: kube-scheduler-gitlab-pointer-pool1-cczkf-rc752
  namespace: kube-system
  ownerReferences:
    - apiVersion: v1
      controller: true
      kind: Node
      name: gitlab-pointer-pool1-cczkf-rc752
      uid: db6214ad-a078-4bc4-adf6-48ab1c429981
  resourceVersion: '1195997'
  uid: d64eddbd-ed98-4b9e-8ed0-0619f3398856
spec:
  containers:
    - args:
        - '--permit-port-sharing=true'
        - >-
          --authentication-kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
        - >-
          --authorization-kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
        - '--bind-address=127.0.0.1'
        - '--cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler'
        - '--kubeconfig=/var/lib/rancher/rke2/server/cred/scheduler.kubeconfig'
        - '--profiling=false'
        - '--secure-port=10259'
        - >-
          --tls-cert-file=/var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
        - >-
          --tls-private-key-file=/var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key
      command:
        - kube-scheduler
      env:
        - name: FILE_HASH
          value: 11cc3e9ebabe6527367da8f93588bb412fb61b155fe12d6f87784541a64b9859
        - name: NO_PROXY
          value: .svc,.cluster.local,10.42.0.0/16,10.43.0.0/16
      image: >-
        registry.rancher.com/rancher/hardened-kubernetes:v1.31.9-rke2r1-build20250515
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 8
        httpGet:
          host: localhost
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 15
      name: kube-scheduler
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext:
        privileged: false
      startupProbe:
        failureThreshold: 24
        httpGet:
          host: localhost
          path: /healthz
          port: 10259
          scheme: HTTPS
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/lib/rancher/rke2/server/db/etcd/name
          name: file0
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
          name: file1
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/tls/client-scheduler.crt
          name: file2
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/tls/client-scheduler.key
          name: file3
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
          name: file4
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key
          name: file5
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/tls/server-ca.crt
          name: file6
          readOnly: true
        - mountPath: /var/lib/rancher/rke2/server/tls/kube-scheduler
          name: extra-mount-0
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: gitlab-pointer-pool1-cczkf-rc752
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      operator: Exists
  volumes:
    - hostPath:
        path: /var/lib/rancher/rke2/server/db/etcd/name
        type: File
      name: file0
    - hostPath:
        path: /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
        type: File
      name: file1
    - hostPath:
        path: /var/lib/rancher/rke2/server/tls/client-scheduler.crt
        type: File
      name: file2
    - hostPath:
        path: /var/lib/rancher/rke2/server/tls/client-scheduler.key
        type: File
      name: file3
    - hostPath:
        path: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt
        type: File
      name: file4
    - hostPath:
        path: /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.key
        type: File
      name: file5
    - hostPath:
        path: /var/lib/rancher/rke2/server/tls/server-ca.crt
        type: File
      name: file6
    - hostPath:
        path: /var/lib/rancher/rke2/server/tls/kube-scheduler
        type: Directory
      name: extra-mount-0
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2025-06-12T15:36:04Z'
      status: 'True'
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: '2025-06-12T15:36:03Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2025-06-12T15:36:14Z'
      status: 'True'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2025-06-12T15:36:14Z'
      status: 'True'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2025-06-12T15:36:03Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        containerd://c85548a61032c04fce8446b7c8f9b3bd5f586066121e55945f1923ab1ce614ba
      image: >-
        registry.rancher.com/rancher/hardened-kubernetes:v1.31.9-rke2r1-build20250515
      imageID: >-
        registry.rancher.com/rancher/hardened-kubernetes@sha256:248efcffbb4de0dc17c307817cd9666f15eb7cf368d61275c1b69bca3bd1ea97
      lastState:
        terminated:
          containerID: >-
            containerd://41953bfe6e0b73d8f8fa37cd43a6b5f3d70a90fa787ab69319faed672accf3fd
          exitCode: 255
          finishedAt: '2025-06-12T15:35:59Z'
          reason: Unknown
          startedAt: '2025-06-12T07:31:07Z'
      name: kube-scheduler
      ready: true
      restartCount: 1
      started: true
      state:
        running:
          startedAt: '2025-06-12T15:36:03Z'
  hostIP: 172.31.36.13
  hostIPs:
    - ip: 172.31.36.13
  phase: Running
  podIP: 172.31.36.13
  podIPs:
    - ip: 172.31.36.13
  qosClass: Burstable
  startTime: '2025-06-12T15:36:03Z'
